namespace: kubeflow
resources:
- vizier-core-deployment.yaml
- vizier-core-rbac.yaml
- vizier-core-rest-deployment.yaml
- vizier-core-rest-service.yaml
- vizier-core-service.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: gcr.io/kubeflow-images-public/katib/vizier-core
    newName: aiven86/kubeflow-images-public_katib_vizier-core
    newTag: v0.1.2-alpha-156-g4ab3dbd
  - name: gcr.io/kubeflow-images-public/katib/vizier-core-rest
    newName: aiven86/kubeflow-images-public_katib_vizier-core-rest
    newTag: v0.1.2-alpha-156-g4ab3dbd
