namespace: kubeflow
resources:
- metrics-collector-rbac.yaml
- metrics-collector-template-configmap.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: gcr.io/kubeflow-images-public/katib/v1alpha2/metrics-collector
    newName: aiven86/kubeflow-images-public_katib_v1alpha2_metrics-collector
    newTag: v0.1.2-alpha-289-g14dad8b
