apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tf-mnist-volume
  namespace: kubeflow 
  labels:
    app: tfjob
spec:
  storageClassName: csi-s3 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

