namespace: kubeflow
resources:
- metrics-collector-rbac.yaml
- metrics-collector-template-configmap.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: gcr.io/kubeflow-images-public/katib/metrics-collector
    newName: aiven86/kubeflow-images-public_katib_metrics-collector
    newTag: v0.1.2-alpha-157-g3d4cd04
